# Buildpacks to include in builder
[[buildpacks]]
uri = "../../../buildpacks/quarkus"

[[order]]
    [[order.group]]
    id = "io.quarkus.buildpacks.buildpack"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.quarkus.buildpacks.stack.jvm"
run-image = "codejive/buildpacks-quarkus-run:jvm"
build-image = "codejive/buildpacks-quarkus-build:jvm"
