# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install the buildpack's pack command
      - name: Install pack
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      # Create the buildpacks
      - name: Create buildpacks
        run: ./create-buildpacks.sh

      # Test the buildpacks
      - name: Build example app (JVM)
        run: pack build quarkus-jvm-test-app --path apps/quarkus-test-app --builder codejive/buildpacks-quarkus-builder:jvm
      - name: Build example app (native)
        run: pack build quarkus-native-test-app --path apps/quarkus-test-app --builder codejive/buildpacks-quarkus-builder:native

      # Test the resulting images
      - name: Run example app (JVM)
        run: docker run -t --rm quarkus-jvm-test-app
      - name: Run example app (native)
        run: docker run -t --rm quarkus-native-test-app
